version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/fe-devpool
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: /aws_codedeploy/install.sh
      timeout: 3000
      runas: root
  AfterInstall:
    - location: /aws_codedeploy/post_install.sh
      timeout: 5000
      runas: ec2-user
  ApplicationStart:
    - location: /aws_codedeploy/run.sh
      timeout: 1200
      runas: ec2-user
  ApplicationStop:
    - location: /aws_codedeploy/stop.sh
      timeout: 1200
      runas: ec2-user
  ValidateService:
    - location: /aws_codedeploy/validate.sh
      timeout: 1200
      runas: ec2-user